### ISSUE TITLE
Updating to Flutter 2.8 falls with error

### ISSUE THREAD

**Issue by WiRight** [jpnurmi/cupertino_list_tile#13]
```
Error: A value of type 'bool?' can't be returned from a function with return type 'bool' because 'bool?' is nullable and 'bool' isn't.
    return dense ?? tileTheme.dense;
```

File: cupertino_list_tile-0.2.0/lib/src/list_tile.dart:139:18

**Comment by WiRight** [comment]
Also found `Error: A value of type 'ListTileThemeData' can't be assigned to a variable of type 'ListTileTheme'.`

**Comment by jpnurmi** [comment]
v0.2.1 published: https://pub.dev/packages/cupertino_list_tile/versions/0.2.1
