### ISSUE TITLE
 Error: No named parameter with the name 'nullOk'.

### ISSUE THREAD

**Issue by SuleymanKeles** [jpnurmi/cupertino_list_tile#6]
The package example project does not work either. I get the following error.

`../pub-cache/hosted/pub.dartlang.org/cupertino_list_tile-0.1.4/lib/src/list_tile_background.dart:266:32: Error: No named parameter with the name 'nullOk'.
        MediaQuery.of(context, nullOk: true)?.navigationMode ??
                               ^^^^^^
../src/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {
                        ^^
../src/flutter/.pub-cache/hosted/pub.dartlang.org/cupertino_list_tile-0.1.4/lib/src/list_tile_background.dart:357:32: Error: No named parameter with the name 'nullOk'.
        MediaQuery.of(context, nullOk: true)?.navigationMode ??
                               ^^^^^^
../src/flutter/packages/flutter/lib/src/widgets/media_query.dart:814:25: Context: Found this candidate, but the arguments don't match.
  static MediaQueryData of(BuildContext context) {`

**Comment by jpnurmi** [comment]
There are some API changes in Flutter. Which version of Flutter are you using? Could you post the output of `flutter doctor -v` please?

**Comment by SuleymanKeles** [comment]
`[√] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.24.0-7.0.pre at C:\..\..\..\src\flutter
    • Framework revision a0860f6e87 (2 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\..\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\..\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\suleyman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • RNE L01 (mobile) • 2VN5T18419015104 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
`

**Comment by SuleymanKeles** [comment]
> There are some API changes in Flutter. Which version of Flutter are you using? Could you post the output of `flutter doctor -v` please?

Of course. I forgot to add.

`[√] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.24.0-7.0.pre at C:\..\..\..\SDK kurulum\src\flutter
    • Framework revision a0860f6e87 (2 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\..\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\..\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.47.3)
    • VS Code at C:\Users\..\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (1 available)
    • RNE L01 (mobile) • 2VN5T18419015104 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
`

**Comment by SuleymanKeles** [comment]
The solution is to change the flutter channels.
